services:

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Activities
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306


  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 8080:8080


  flask:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+mysqldb://root:admin@db:3306/Activities
    ports:
      - 5000:5000
    depends_on:
      - db